---
name: ci

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  prechecks:
    uses: ./.github/workflows/pre-commit.yml
  all-prechecks:
    needs: [prechecks]
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        run: "true"
  tests:
    needs: [all-prechecks]
    uses: ./.github/workflows/build_and_test.yml
    with:
      core_ref: >-
        ${{
          startsWith(github.head_ref || github.ref_name, 'coll-work-')
          && '4bc0c2d96395b0f5a1d5337cd0520924c67e42d5'
          || 'devel'
        }}
      core_repository: >-
        ${{
          startsWith(github.head_ref || github.ref_name, 'coll-work-')
          && 'nab880/sst-core'
          || 'sstsimulator/sst-core'
        }}
    permissions:
      actions: write
  all-tests:
    needs: [tests]
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        run: "true"
